import { SKILL } from '@/lib/data/skills';

import { defineProject } from '../types';

export const camerafiStudioProject = defineProject({
  id: 'camerafi_studio',
  slug: 'camerafi-studio',
  section: 'work',
  parentId: 'vault_micro',
  dateFrom: '2022-02',
  dateTo: '2023-06',
  detailPath: '/projects/camerafi-studio',
  paradigm: 'assisted',
  featuredSkills: [
    SKILL.languages.typescript,
    SKILL.frameworks.nextJs,
    SKILL.state.tanstackQuery,
    SKILL.state.reactHookForm,
    SKILL.backend.paddle,
    SKILL.devops.webpack,
  ],
  skills: [
    SKILL.languages.typescript,
    SKILL.frameworks.nextJs,
    SKILL.ui.styledComponents,
    SKILL.ui.mui,
    SKILL.state.tanstackQuery,
    SKILL.state.reactHookForm,
    SKILL.backend.firebase,
    SKILL.backend.paddle,
    SKILL.devops.githubActions,
    SKILL.devops.webpack,
  ],
  content: {
    en: {
      title: 'CameraFi Studio',
      description: 'Web Overlay Scoreboard Service',
      summaryDetails: [
        '**[Production SaaS Scope]** Built a production web service spanning overlay editing, authenticated dashboards, i18n, subscription checkout, webhook-based renewal handling, and cookie consent flows.',
        '**[Bundle Size Optimization]** Reduced main bundle size by 15% (324KB → 277KB) and improved TTI by establishing Webpack Tree Shaking & Code Splitting strategies and applying Dynamic Import.',
        '**[Secure Auth Architecture]** Designed a secure login process combining **Firebase Custom Tokens** and **HTTP-only Cookies** to synchronize auth state between client and server.',
        '**[Global SaaS Infrastructure]** Built the entire payment lifecycle using **Paddle**, handling subscriptions and webhook-based renewal processing for a global B2B user base.',
        '**[Custom Cookie Consent]** Developed a native cookie consent banner and control logic from scratch to comply with GDPR/web standards without relying on external scripts, preventing 3rd-party bloat.',
      ],
      detailMetadata: {
        title: 'CameraFi Studio',
        description:
          "Web-based broadcast overlay platform built solo — from frontend architecture to the company's second main revenue stream.",
        date: '2022-02 ~ 2023-06',
        image: '/images/camerafi-studio/optimization_chart.webp',
        productLink: 'https://studio.camerafi.com',
        role: 'Frontend Engineer',
        platforms: ['Web'],
        metrics: [
          { value: '15%', label: 'Bundle Size Reduced' },
          { value: '47KB', label: 'JS Saved' },
        ],
        techStack: [
          'TypeScript',
          'Next.js',
          'styled-components',
          'MUI',
          'TanStack Query',
          'React Hook Form',
          'Firebase',
          'Paddle',
          'GitHub Actions',
          'Webpack',
        ],
      },
    },
    ko: {
      title: '카메라파이 스튜디오',
      description: '웹 기반 방송용 오버레이 스코어보드 서비스',
      summaryDetails: [
        '**[프로덕션 SaaS 범위]** 오버레이 에디터, 인증 대시보드, i18n, 구독 결제, 웹훅 기반 갱신 처리, 쿠키 동의 플로우까지 포함한 실제 운영 웹 서비스를 구축했습니다.',
        '**[번들 사이즈 최적화]** Webpack 트리 쉐이킹 및 코드 스플리팅 전략을 수립하고 **Dynamic Import를 적용하여 메인 번들 사이즈를 15% 감량**, TTI를 단축했습니다.',
        '**[보안 인증 아키텍처]** **Firebase Custom Token과 HTTP-only Cookie**를 결합한 인증 프로세스를 설계하여 클라이언트와 서버 간의 인증 상태를 안전하게 동기화했습니다.',
        '**[글로벌 수익화 인프라]** **Paddle 결제 모듈을 연동**하여 글로벌 사용자를 위한 구독 상태 관리 및 웹훅 기반의 결제 갱신 처리 시스템을 구축했습니다.',
        '**[자체 쿠키 동의 시스템]** 서드파티 스크립트 없이 **GDPR 규정을 준수하는 쿠키 동의 배너와 제어 로직을 직접 개발**하여 불필요한 외부 라이브러리 의존성을 제거했습니다.',
      ],
      detailMetadata: {
        title: 'CameraFi Studio',
        description:
          '1인 개발로 설계한 웹 기반 방송 오버레이 플랫폼 — 프론트엔드 아키텍처부터 사내 두 번째 핵심 수익 모델까지.',
        date: '2022-02 ~ 2023-06',
        image: '/images/camerafi-studio/optimization_chart.webp',
        productLink: 'https://studio.camerafi.com',
        role: 'Frontend Engineer',
        platforms: ['Web'],
        metrics: [
          { value: '15%', label: '번들 사이즈 감소' },
          { value: '47KB', label: 'JS 절감' },
        ],
        techStack: [
          'TypeScript',
          'Next.js',
          'styled-components',
          'MUI',
          'TanStack Query',
          'React Hook Form',
          'Firebase',
          'Paddle',
          'GitHub Actions',
          'Webpack',
        ],
      },
    },
  },
});
