allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

minimumReleaseAge: 1440
trustPolicy: no-downgrade
trustPolicyExclude:
  - "eslint-import-resolver-typescript@3.10.1"
  - "semver@6.3.1"
blockExoticSubdeps: true

