name = "svelte-blog"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "portfolio-assets"
bucket_name = "portfolio-assets"

[[d1_databases]]
binding = "portfolio_db"
database_name = "portfolio-db"
database_id = "3c7cc643-2ad9-4c9a-97c3-2e2105b3e8ef"
