import { SKILL } from '$lib/data/skills';

import { defineProject } from '../types';

export const airaProject = defineProject({
  id: 'aira',
  slug: 'aira',
  section: 'work',
  parentId: 'orca_ai',
  dateFrom: '2024-07',
  dateTo: '2025-12',
  detailPath: '/projects/aira',
  paradigm: 'assisted',
  featuredSkills: [
    SKILL.languages.typescript,
    SKILL.frameworks.reactNative,
    SKILL.frameworks.expo,
    SKILL.state.tanstackQuery,
    SKILL.performance.flashList,
    SKILL.devops.eas,
  ],
  skills: [
    SKILL.languages.typescript,
    SKILL.frameworks.reactNative,
    SKILL.frameworks.expo,
    SKILL.frameworks.expoRouter,
    SKILL.ui.unistyles,
    SKILL.ui.lottie,
    SKILL.state.tanstackQuery,
    SKILL.state.reactHookForm,
    SKILL.state.zod,
    SKILL.state.reactNativeMmkv,
    SKILL.performance.flashList,
    SKILL.performance.reactNativeReanimated,
    SKILL.performance.reactCompiler,
    SKILL.backend.firebase,
    SKILL.devops.githubActions,
    SKILL.devops.eas,
    SKILL.devops.sentry,
    SKILL.aiWorkflow.agenticWorkflow,
    SKILL.aiWorkflow.claudeCode,
    SKILL.aiWorkflow.cursor,
    SKILL.aiWorkflow.gemini,
  ],
  content: {
    en: {
      title: 'aira',
      description: 'Global AI Character Chat Platform',
      metrics: [
        { value: '23k', label: 'MAU (Peak)' },
        { value: '$3,000', label: 'Monthly Revenue' },
        { value: '46 min', label: 'Avg. Session' },
      ],
      summaryDetails: [
        "**[Key Achievements]** Achieved 23k MAU and $3,000 monthly revenue with an average session time of 46 minutes — ranked 57th in Google Play Entertainment (as of Feb '25).",
        '**[Ownership Scope]** Owned the frontend architecture from product planning to release operations, including chat UX, server-state design, EAS/TestFlight delivery, Sentry monitoring, and monetization UI.',
        '**[Streaming Chat & Optimistic UI]** Validated stream chunks at runtime with **Zod** and patched TanStack Query **InfiniteQuery** cache in real-time per chunk to create typing animations. Applied optimistic update pattern via `onMutate` for instant message insertion with rollback on failure.',
        '**[Type-Safe Server State Management]** Designed a **queryData facade** that structures `QueryClient` access by domain, providing hierarchical query key factories for bulk invalidation and type-safe cache get/update/delete operations.',
        '**[Data Persistence & Cache Isolation]** Migrated on-device (Realm) → server (RDB) data without loss using retry logic and transaction flags. Separated **MMKV** into purpose-specific instances (document, cache, settings) and auto-isolated per-user caches via `PersistQueryClientProvider` `buster: uid`.',
        '**[Rendering Performance Optimization]** Maintained stable 60 FPS with **FlashList** View Recycling and **React Compiler**. Handled keyboard-open scroll on the UI thread via **Reanimated** worklet-based `useAnimatedReaction`, eliminating JS thread bottlenecks.',
        '**[Cross-Platform Architecture]** Supported Android, iOS, and Web simultaneously from a single codebase using **Expo Router**. Separated platform-specific Contexts via `.web.tsx` file extensions to prevent native-only packages from leaking into the web bundle. Auto-bound **Unistyles** tokens to React Navigation `ThemeProvider` for synchronized theme switching.',
        '**[Design Token System]** Implemented numeric-scale color palettes and dark/light/auto themes with **Unistyles**. Eliminated theme flicker on app restart via MMKV synchronous reads. Applied fontScale clamping (1–1.2) for accessibility-safe layouts.',
        '**[Type-Safe i18n]** Enforced compile-time translation key validation with **typesafe-i18n** and deferred rendering until Intl polyfills fully loaded to prevent locale glitches. Synchronized OS settings and dayjs on language switch.',
        '**[UX-Centric Monetization]** Designed **Native Ads** UI to prevent CLS and monitored drop-off rates to achieve revenue growth without compromising the user experience.',
        '**[Service Stability]** Built a precise error tracking environment by integrating Sentry and dSYM, and prevented user churn with a rapid rollback process when Android-specific issues arose.',
        '**[Operational Efficiency]** Built CI/CD pipelines using **EAS** and **GitHub Actions** (automated Android closed-track deployment, iOS TestFlight) and established a device compatibility testing process via **Samsung Test Lab**.',
      ],
      detailMetadata: {
        title: 'aira',
        description:
          'Global AI character chat platform. Led the entire journey from planning to 23k MAU as Co-Founder and Frontend Lead.',
        role: 'Co-Founder · Frontend Lead',
        date: '2024-07 ~ 2025-12',
        image: '/images/aira/v2_main.webp',
        platforms: ['Android', 'iOS', 'Web'],
        metrics: [
          { value: '23K', label: 'Monthly Active Users' },
          { value: '$3K', label: 'Monthly Revenue' },
          { value: '46min', label: 'Avg. Session Time' },
          { value: '#57', label: 'GP Entertainment' },
        ],
        techStack: [
          'React Native',
          'TypeScript',
          'Expo',
          'Expo Router',
          'TanStack Query',
          'FlashList',
          'Reanimated',
          'React Compiler',
          'Zod',
          'MMKV',
          'Unistyles',
          'Firebase',
          'Sentry',
          'React Hook Form',
          'Lottie',
          'GitHub Actions',
          'EAS',
          'Cursor',
          'Gemini',
        ],
      },
    },
    ko: {
      title: '아이라 (aira)',
      description: '글로벌 AI 캐릭터 채팅 플랫폼',
      metrics: [
        { value: '2.3만', label: '최고 MAU' },
        { value: '$3,000', label: '월 매출' },
        { value: '46분', label: '평균 체류 시간' },
      ],
      summaryDetails: [
        '**[주요 성과]** **MAU 2.3만 명, 월 매출 $3,000, 평균 체류 시간 46분** 달성 — 구글 플레이 엔터테인먼트 부문 최고 57위 기록 (25년 2월 기준).',
        '**[오너십 범위]** 제품 기획부터 프론트엔드 아키텍처, 채팅 UX, 서버 상태 설계, EAS/TestFlight 배포, Sentry 모니터링, 수익화 UI까지 출시 운영 전반을 맡았습니다.',
        '**[스트리밍 채팅 및 낙관적 UI]** 스트림 청크를 **Zod**로 실시간 검증하고, TanStack Query **InfiniteQuery** 캐시를 직접 패치하여 **끊김 없는 타이핑 애니메이션**을 구현했습니다. `onMutate`를 통한 **낙관적 업데이트**로 즉각적인 피드백을 제공했습니다.',
        '**[타입 안전한 캐시 파사드]** QueryClient를 직접 다루는 대신 도메인별로 구조화된 **queryData 파사드**를 설계했습니다. 계층적 쿼리 키 팩토리를 통해 **일괄 무효화 및 타입 안전한 CRUD** 작업을 수행합니다.',
        '**[데이터 영속화 및 격리]** Realm에서 서버 DB로 대화 데이터를 **무유실 마이그레이션**했습니다. **MMKV**를 용도별 인스턴스로 분리하고, `PersistQueryClientProvider`의 `buster` 옵션으로 **사용자별 캐시를 자동 격리**했습니다.',
        '**[렌더링 성능 최적화]** **FlashList**의 뷰 재사용과 **React Compiler** 도입으로 **60 FPS의 성능**을 유지했습니다. 키보드 오픈 시의 스크롤 처리를 **Reanimated** 워클릿을 통해 **UI 스레드에서 직접 처리**하여 병목을 제거했습니다.',
        '**[크로스 플랫폼 아키텍처]** **Expo Router**를 기반으로 하나의 코드로 앱과 웹을 동시 지원합니다. `.web.tsx` 확장자를 활용해 플랫폼별 컨텍스트를 분리하고, **Unistyles** 토큰을 테마 시스템에 자동 바인딩했습니다.',
        '**[디자인 토큰 시스템]** **Unistyles**로 숫자 스케일 기반 팔레트와 다크/라이트 테마를 구축했습니다. **MMKV 동기 읽기**로 앱 재시작 시 테마 깜빡임을 해결하고, 접근성 설정을 고려한 **폰트 스케일링 유틸**을 적용했습니다.',
        '**[타입 안전한 i18n]** **typesafe-i18n**으로 번역 키를 컴파일 타임에 검증합니다. Intl 폴리필 로드 완료 전까지 렌더링을 차단하여 로케일 오작동을 방지하고, 언어 전환 시 OS 설정을 동기화했습니다.',
        '**[비즈니스 모델 구축]** 레이아웃 시프트를 방지한 **네이티브 광고 UI** 설계 및 결제 전환율 모니터링을 통해 **사용자 경험을 해치지 않는 수익 성장**을 이끌어냈습니다.',
        '**[서비스 안정성]** Sentry와 dSYM 연동으로 **정밀한 에러 추적 환경**을 구축하고, 안드로이드 특정 기기 이슈 발생 시 신속한 롤백 프로세스를 통해 유저 이탈을 방지했습니다.',
        '**[운영 효율화]** **EAS와 GitHub Actions**로 안드로이드 폐쇄 테스트 및 iOS TestFlight **배포 파이프라인을 자동화**하고, **삼성 테스트랩**을 통한 기기 호환성 검증 프로세스를 수립했습니다.',
      ],
      detailMetadata: {
        title: '아이라',
        description:
          '글로벌 AI 캐릭터 채팅 플랫폼. 공동 창업자이자 프론트엔드 리드로서 기획부터 2.3만 MAU 달성까지 전 과정을 주도했습니다.',
        role: 'Co-Founder · Frontend Lead',
        date: '2024-07 ~ 2025-12',
        image: '/images/aira/v2_main.webp',
        platforms: ['Android', 'iOS', 'Web'],
        metrics: [
          { value: '2.3만', label: '월간 활성 사용자' },
          { value: '$3K', label: '월 매출' },
          { value: '46분', label: '평균 체류 시간' },
          { value: '#57', label: 'GP 엔터테인먼트' },
        ],
        techStack: [
          'React Native',
          'TypeScript',
          'Expo',
          'Expo Router',
          'TanStack Query',
          'FlashList',
          'Reanimated',
          'React Compiler',
          'Zod',
          'MMKV',
          'Unistyles',
          'Firebase',
          'Sentry',
          'React Hook Form',
          'Lottie',
          'GitHub Actions',
          'EAS',
          'Cursor',
          'Gemini',
        ],
      },
    },
  },
});
