"""Generate checked-in WOFF2 subsets; requires fonttools[woff] (see media docs)."""
from hashlib import sha256
from pathlib import Path
import json

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "src/app/fonts/WantedSansVariable.woff2"
OUTPUT = ROOT / "public/fonts/wanted"
CSS = ROOT / "src/lib/styles/fonts.generated.css"
MANIFEST = ROOT / "src/lib/generated/fonts.json"


def unicode_ranges(points: set[int]) -> str:
    """Coalesce ranges without declaring glyphs outside this subset."""
    ranges = []
    for point in sorted(points):
        if ranges and point == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], point)
        else:
            ranges.append((point, point))
    return ",".join(
        f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}"
        for start, end in ranges
    )


def main() -> None:
    font = TTFont(SOURCE)
    supported = set(font.getBestCmap())
    font.close()
    text = "".join(
        path.read_text()
        for path in sorted((ROOT / "src").rglob("*"))
        if path.suffix in {".mdx", ".ts", ".tsx"} and "generated" not in path.parts
    )
    latin = {point for point in supported if point <= 0x024F}
    content = {ord(char) for char in text} & supported - latin
    remaining = sorted(supported - latin - content)
    groups = [("latin", latin), ("content", content)] + [
        (f"fallback-{index // 256}", set(remaining[index:index + 256]))
        for index in range(0, len(remaining), 256)
    ]
    OUTPUT.mkdir(parents=True, exist_ok=True)
    rules = []
    assets = []
    for name, points in groups:
        if not points:
            continue
        options = subset.Options()
        options.flavor = "woff2"
        options.recalc_timestamp = False
        subfont = subset.load_font(str(SOURCE), options)
        subsetter = subset.Subsetter(options)
        subsetter.populate(unicodes=points)
        subsetter.subset(subfont)
        # Hash content to keep immutable font caching safe across regeneration.
        temporary = OUTPUT / f"{name}.woff2"
        subset.save_font(subfont, str(temporary), options)
        subfont.close()
        data = temporary.read_bytes()
        filename = f"{name}-{sha256(data).hexdigest()[:12]}.woff2"
        temporary.replace(OUTPUT / filename)
        url = f"/fonts/wanted/{filename}"
        ranges = unicode_ranges(points)
        rules.append(
            "@font-face {\n  font-family: 'Wanted Sans';\n"
            f"  src: url('{url}') format('woff2');\n"
            "  font-style: normal;\n  font-weight: 400 800;\n  font-display: swap;\n"
            f"  unicode-range: {ranges};\n}}\n"
        )
        assets.append({"name": name, "src": url, "bytes": len(data), "unicodeRange": ranges})
    CSS.write_text("/* Generated by scripts/generate-fonts.py. */\n" + "\n".join(rules))
    MANIFEST.write_text(json.dumps(assets, indent=2) + "\n")
    initial_bytes = sum(asset["bytes"] for asset in assets[:2])
    print(f"Generated {len(assets)} subsets; Latin and content total {initial_bytes:,} bytes.")


if __name__ == "__main__":
    main()
