import { SKILL } from '$lib/data/skills';

import { defineProject } from '../types';

export const mndExcelViewerProject = defineProject({
  id: 'web_viewer',
  slug: 'mnd-excel-viewer',
  section: 'work',
  parentId: 'mnd',
  dateFrom: '2020-08',
  dateTo: '2020-10',
  detailPath: '/projects/mnd-excel-viewer',
  featuredSkills: [
    SKILL.languages.typescript,
    SKILL.frameworks.react,
    SKILL.ui.reactTable,
    SKILL.performance.reactWindow,
    SKILL.performance.reactVirtualized,
    SKILL.backend.socketIo,
  ],
  skills: [
    SKILL.languages.typescript,
    SKILL.frameworks.react,
    SKILL.ui.styledComponents,
    SKILL.ui.atomicDesign,
    SKILL.ui.reactTable,
    SKILL.state.redux,
    SKILL.state.reduxSaga,
    SKILL.performance.reactWindow,
    SKILL.performance.reactVirtualized,
    SKILL.backend.socketIo,
  ],
  content: {
    en: {
      title: 'Web-based Document Viewer',
      description: 'Spreadsheet and text viewer for large intranet documents',
      metrics: [
        { value: '2 Views', label: 'Grid + Text' },
        { value: '1K+ Rows', label: 'Rebuilt Fixtures' },
        { value: '2D', label: 'Range Selection' },
        { value: 'Realtime', label: 'Socket Highlights' },
      ],
      summaryDetails: [
        '**[Dual Viewer Scope]** Built both an Excel-style grid viewer and a line-based text viewer, separating container interaction logic from pure rendering components.',
        '**[Safe Scale Evidence]** Recreated large-document fixtures with **1,000+ rows** to validate virtual scrolling, selection anchors, and heavy-document rendering without exposing private data.',
        '**[High-Performance Virtualization]** Used **react-window** for large grid rows and **react-virtualized** for variable-height text lines, keeping scroll and selection responsive under heavy documents.',
        '**[2D Selection UX]** Implemented rectangular cell selection, reverse line-range normalization, and multi-region drag updates with real-time visual feedback.',
        '**[Real-time Collaboration]** Integrated **Socket.IO** for shared highlights and comments, plus a mock socket layer for development in restricted intranet environments.',
        '**[Atomic Design System]** Established a scalable component library from scratch using **Atomic Design** principles, ensuring UI consistency across the intranet platform.',
      ],
      detailMetadata: {
        title: 'Spreadsheet-style grid & text viewer',
        description:
          'Large-scale grid and line-based text viewer using React Table, virtualization, and 2D cell selection (Immer)',
        date: '2020-08 ~ 2020-10',
        metrics: [
          { value: '2 Views', label: 'Grid + Text' },
          { value: '1K+ Rows', label: 'Rebuilt Fixtures' },
          { value: '2D', label: 'Range Selection' },
          { value: 'Realtime', label: 'Socket Highlights' },
        ],
        role: 'Frontend Engineer',
        techStack: [
          'TypeScript',
          'React',
          'styled-components',
          'Atomic Design',
          'React Table',
          'Redux',
          'Redux-Saga',
          'react-window',
          'react-virtualized',
          'Socket.IO',
        ],
      },
    },
    ko: {
      title: '웹 기반 문서 뷰어',
      description: '인트라넷 대용량 문서를 위한 스프레드시트·텍스트 뷰어',
      metrics: [
        { value: '2 Views', label: '그리드+텍스트' },
        { value: '1K+ 행', label: '재구성 Fixture' },
        { value: '2D', label: '영역 선택' },
        { value: 'Realtime', label: '소켓 하이라이트' },
      ],
      summaryDetails: [
        '**[이중 뷰어 범위]** 엑셀형 그리드 뷰어와 줄 단위 텍스트 뷰어를 함께 구축하고, 컨테이너 상호작용 로직과 순수 렌더링 컴포넌트를 분리했습니다.',
        '**[안전한 규모 근거]** 비공개 데이터를 노출하지 않기 위해 **1,000행 이상 재구성 Fixture**로 가상 스크롤, 선택 앵커, 대용량 렌더링을 검증했습니다.',
        '**[고성능 가상화]** 대용량 그리드는 **react-window**, 가변 높이 텍스트 줄은 **react-virtualized**로 처리해 무거운 문서에서도 스크롤과 선택 응답성을 유지했습니다.',
        '**[2D 영역 선택 UX]** 직사각형 셀 선택, 역방향 줄 범위 정규화, 다중 영역 드래그 업데이트와 실시간 시각 피드백을 구현했습니다.',
        '**[실시간 협업 기능]** **Socket.IO**로 공유 하이라이트와 코멘트를 연동하고, 제한된 인트라넷 환경에서도 개발 가능한 Mock 소켓 레이어를 구축했습니다.',
        '**[Atomic 디자인 시스템]** **Atomic Design 원칙에 따라 컴포넌트 라이브러리를 바닥부터 설계**하여, 인트라넷 플랫폼 전체의 UI 일관성을 확보했습니다.',
      ],
      detailMetadata: {
        title: '스프레드시트형 그리드·텍스트 뷰어',
        description:
          'React Table·가상화·2D 셀 선택(Immer)을 활용한 대용량 그리드와 줄 단위 텍스트 뷰어',
        date: '2020-08 ~ 2020-10',
        metrics: [
          { value: '2 Views', label: '그리드+텍스트' },
          { value: '1K+ 행', label: '재구성 Fixture' },
          { value: '2D', label: '영역 선택' },
          { value: 'Realtime', label: '소켓 하이라이트' },
        ],
        role: 'Frontend Engineer',
        techStack: [
          'TypeScript',
          'React',
          'styled-components',
          'Atomic Design',
          'React Table',
          'Redux',
          'Redux-Saga',
          'react-window',
          'react-virtualized',
          'Socket.IO',
        ],
      },
    },
  },
});
