import { SKILL } from '$lib/data/skills';

import { defineProject } from '../types';

export const onelineBankProject = defineProject({
  id: 'onelinebank_rebuild',
  slug: 'oneline-bank',
  section: 'other',
  dateFrom: '2021-04',
  dateTo: '2021-04',
  detailPath: '/projects/oneline-bank',
  featuredSkills: [
    SKILL.languages.typescript,
    SKILL.frameworks.expo,
    SKILL.state.tanstackForm,
    SKILL.state.zod,
    SKILL.devops.eas,
    SKILL.devops.crashlytics,
  ],
  skills: [
    SKILL.languages.typescript,
    SKILL.frameworks.reactNative,
    SKILL.frameworks.expo,
    SKILL.frameworks.expoRouter,
    SKILL.ui.tailwindCss,
    SKILL.ui.cva,
    SKILL.state.tanstackQuery,
    SKILL.state.tanstackForm,
    SKILL.state.zod,
    SKILL.state.zustand,
    SKILL.state.reactNativeMmkv,
    SKILL.performance.reactNativeReanimated,
    SKILL.backend.firebase,
    SKILL.devops.eas,
    SKILL.devops.crashlytics,
  ],
  content: {
    en: {
      title: 'OnelineBank',
      titleBadge: '2021 Hackathon Finalist',
      description:
        'Advanced to the 2021 Woori Bank Hackathon finals by independently building a fintech app in 5 days. In 2026, fully rewrote the original JavaScript codebase from scratch in TypeScript with a modern stack.',
      summaryDetails: [
        '**[Architecture Evolution]** Rebuilt a legacy JS app into a modular, feature-based architecture using **TypeScript** and **Expo Router**, applying production-grade design patterns.',
        '**[Robust Form Handling]** Integrated **TanStack Form** and **Zod** for type-safe schema validation and consistent error handling across the banking flow.',
        '**[Developer Experience]** Optimized the delivery pipeline using **EAS** and automated crash reporting with **Crashlytics**, ensuring a stable demo environment.',
      ],
      detailMetadata: {
        title: 'OnelineBank',
        description:
          'Conversational mobile banking demo — 2021 Woori Bank hackathon app rebuilt in TypeScript with Expo Router, TanStack Query, and feature-based modules.',
        date: '2021-04',
        image: '/images/oneline-bank/1.webp',
        githubLink: 'OnelineBank',
        role: 'Solo developer',
        platforms: ['Android', 'iOS'],
        techStack: [
          'React Native',
          'TypeScript',
          'Expo',
          'Expo Router',
          'TanStack Query',
          'TanStack Form',
          'Zustand',
          'Tailwind CSS',
          'Zod',
          'MMKV',
          'Firebase',
          'Reanimated',
          'CVA',
          'EAS',
          'Crashlytics',
        ],
      },
    },
    ko: {
      title: '한줄은행 (리빌드)',
      titleBadge: '2021 해커톤 본선 진출작',
      description:
        '2021 우리은행 해커톤 출품작을 최신 기술 스택인 TypeScript, Expo Router 등으로 전면 재구성한 성장 스토리 기반 프로젝트.',
      summaryDetails: [
        '**[아키텍처의 진화]** 레거시 JS 앱을 **TypeScript와 Expo Router 기반의 기능 단위(Feature-based) 모듈 아키텍처**로 리빌딩하여 생산성을 극대화했습니다.',
        '**[견고한 폼 핸들링]** **TanStack Form과 Zod를 결합**하여 타입 안전한 스키마 검증과 일관된 에러 피드백 시스템을 뱅킹 플로우에 적용했습니다.',
        '**[개발자 경험 개선]** **EAS를 통한 배포 자동화와 Crashlytics 연동**으로 안정적인 데모 환경과 장애 추적 인프라를 구축했습니다.',
      ],
      detailMetadata: {
        title: '한줄은행',
        description:
          '대화형 모바일 뱅킹 데모 — 2021 우리은행 해커톤 출품작을 TypeScript·Expo Router·TanStack Query·기능 모듈 구조로 전면 재작성했습니다.',
        date: '2021-04',
        image: '/images/oneline-bank/1.webp',
        githubLink: 'OnelineBank',
        role: '1인 개발',
        platforms: ['Android', 'iOS'],
        techStack: [
          'React Native',
          'TypeScript',
          'Expo',
          'Expo Router',
          'TanStack Query',
          'TanStack Form',
          'Zustand',
          'Tailwind CSS',
          'Zod',
          'MMKV',
          'Firebase',
          'Reanimated',
          'CVA',
          'EAS',
          'Crashlytics',
        ],
      },
    },
  },
});
